--- # Ansible Facts exampls
- hosts: web
  tasks:
    - name: Create file
      lineinfile:
        path: /home/cloud_user/hostname
        create: yes
        line: "{{ ansible hostname }}"
    - name: access magic variable
      lineinfile:
        path: /home/cloud_user/hostname
        line: "{{  hostvars['localhost']['ansible_default_ipv4']['address']  }}"
